name: CI

on:
  push:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.9', '3.12']
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5.1.0
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Poetry
        uses: snok/install-poetry@v1.3.4
      - name: Install Python dependencies
        working-directory: flask_app
        run: |
          python -m pip install --upgrade pip
          poetry install
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      # run npm install
      - name: Install node dependencies and Google Chrome
        working-directory: angular-app
        run: |
          npm install
          # Need chrome for Angular tests
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
          # copy over the environment.ts, otherwise tests will fail.
          cp src/environments/environment.ts.template src/environments/environment.ts
      - name: Run pre-commit
        run: poetry run pre-commit run --all-files
      - name: Run Python Tests
        run: poetry run pytest
      - name: Run Angular Tests
        working-directory: angular-app
        run: |
          # install angular cli
          npm install -g @angular/cli@17
          ng test --watch=false --browsers=ChromeHeadless
