name: CI

on:
  push:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.9', '3.12']
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5.1.0
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Poetry
        uses: snok/install-poetry@v1.3.4
      - name: Install Python dependencies
        working-directory: flask-app
        run: |
          python -m pip install --upgrade pip
          poetry install
      - name: Run pre-commit
        working-directory: flask-app
        run: poetry run pre-commit run --all-files
