name: CI

on:
  push:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.9", "3.12"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5.1.0
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Poetry
        uses: snok/install-poetry@v1.3.4
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          cd flask-app && poetry install        
      - name: Run pre-commit
        run: poetry run pre-commit run --all-files
      - name: Run notebook and check for completion
        env:
          TEST_DATA: "true"
        run: poetry run jupyter nbconvert --to html --execute analysis_california_eci.ipynb --output test_output-${{ github.run_id }}.html
      - name: Upload HTML Artifact
        if: ${{ matrix.python-version == '3.12' }}
        uses: actions/upload-artifact@v4
        with:
          name: notebook-html-${{ github.run_id }}
          path: test_output-${{ github.run_id }}.html
